ARG DEBIAN_FRONTEND=noninteractive
ARG INIT_PATH=/usr/local/bin/dumb-init
ARG INIT_URL=https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64
ARG USERNAME=rust
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG WORK_DIR=/usr/src/app

FROM rust:1.80.1 AS dev

ARG DEBIAN_FRONTEND
ARG INIT_PATH
ARG INIT_URL
ARG USERNAME
ARG USER_UID
ARG USER_GID
ARG WORK_DIR

ENV TZ=America/Sao_Paulo TERM=xterm-256color LANG=C.UTF-8 LC_ALL=C.UTF-8

SHELL [ "/bin/bash", "-c" ]

RUN set -euxo pipefail;\
  apt-get -qq update;\
  apt-get -qq install -y nano sudo apt-utils build-essential tzdata curl cmake g++ libpcre3-dev libssl-dev make openssl libgmp-dev git curl ca-certificates software-properties-common wget zip unzip busybox > /dev/null;\
  curl --fail --silent --show-error --location ${INIT_URL} --output ${INIT_PATH};\
  apt-get -qq clean;\
  chmod +x ${INIT_PATH};\
  cargo install cargo-watch;

RUN set -euxo pipefail;\
  groupadd --gid $USER_GID $USERNAME;\
  useradd --uid $USER_UID --gid $USER_GID -m $USERNAME;\
  echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME;\
  chmod 0440 /etc/sudoers.d/$USERNAME;

USER ${USERNAME}

ENV CARGO_HOME="/home/${USERNAME}/.cargo"

WORKDIR $WORK_DIR

EXPOSE 3000

ENTRYPOINT [ "/usr/local/bin/dumb-init", "--" ]

CMD [ "cargo", "watch", "-w", "src", "-x", "run" ]
